notifications:
  email: false
language: elixir
elixir:
  - 1.5.1
otp_release:
  - 20.0
services:
  - postgresql
env:
  MIX_ENV=test
before_script:
  - psql -c 'create database short_test_repo;' -U postgres
  - mix do short.ecto.install, ecto.migrate
